defaultPortal: diagramjay
portals:
  - name: diagramjay
    portalId: 213744
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIen8f7xLxIIAAUAAAAAAAwY8IUNINfX8ggo7ukMMhSHAVzH_4Yg_TSBoCvla--FL1G_RTohAAAEQQAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAA8QhSttpOYtyut4DXmmOua_QDw_oDwxUoDbmExUgBaAA
        expiresAt: '2022-02-22T05:16:47.385Z'
    personalAccessKey: >-
      CiRkMGU4MmM2NC1jZTJkLTQ1MTItOTBjZS02NWRmYTVlOTk2ZjQQ8IUNGNfX8ggqGQAF5pGC59xizfWGSNHpeyNOdZWujom2hINKA25hMQ
