defaultPortal: diagramjay
portals:
  - name: diagramjay
    portalId: 213744
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIazo_7xLxIIAAUAAAAAAAwY8IUNINfX8ggo7ukMMhTJxLuROiUDVzIxEDta5-9RxAmljTohAAAEQQAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAA8QhTXiR0pSyi-Rqo7P5M6aRS0fPzDg0oDbmExUgBaAA
        expiresAt: '2022-02-22T04:55:30.956Z'
    personalAccessKey: >-
      CiRkMGU4MmM2NC1jZTJkLTQ1MTItOTBjZS02NWRmYTVlOTk2ZjQQ8IUNGNfX8ggqGQAF5pGC59xizfWGSNHpeyNOdZWujom2hINKA25hMQ
