defaultPortal: diagramjay
portals:
  - name: diagramjay
    portalId: 213744
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COWGo__xLxIIAAUAAAAAAAwY8IUNINfX8ggo7ukMMhSdtVWr5VgV1VaFCHzyGf-jiKSZBTohAAAEQQAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAA8QhT69dJVJnp3mBGpOHwHFg_fgPxIskoDbmExUgBaAA
        expiresAt: '2022-02-22T05:30:22.442Z'
    personalAccessKey: >-
      CiRkMGU4MmM2NC1jZTJkLTQ1MTItOTBjZS02NWRmYTVlOTk2ZjQQ8IUNGNfX8ggqGQAF5pGC59xizfWGSNHpeyNOdZWujom2hINKA25hMQ
